version: "3"

services:
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                                N O D E J S                               #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#               
    nodejs:
        build: .
        image: tchatperche_node
        container_name: 'tchatperche_nodejs'
        # restart: always
        depends_on:
            - mongodb
        ports:
            - 80:8080
        volumes:
            - ./app:/usr/src/app

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                               M O N G O D B                              #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
    mongodb:
        image: mongo:latest
        container_name: 'tchatperche_mongodb'
        # restart: always
        ports: 
            - 27018:27017
        # volumes:
            # - ./mongodb:/data/db
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=tchatperche
            - MONGO_INITDB_ROOT_PASSWORD=tp_pswd

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#               
